
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignupWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QtCore.QSize(1500, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(700, 0))
        self.frame.setStyleSheet("background-color: rgb(180, 100, 206);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(40)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4.addWidget(self.frame_9)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(48)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(4, 49, 51);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setMinimumSize(QtCore.QSize(300, 0))
        self.label_6.setStyleSheet("image: url(:/icons/media/Color logo black - no background.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setStyleSheet("color: rgb(77, 89, 89);")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.name_entry = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_entry.sizePolicy().hasHeightForWidth())
        self.name_entry.setSizePolicy(sizePolicy)
        self.name_entry.setMinimumSize(QtCore.QSize(0, 50))
        self.name_entry.setStyleSheet("background-color: rgb(239, 240, 242);")
        self.name_entry.setInputMask("")
        self.name_entry.setFrame(False)
        self.name_entry.setObjectName("name_entry")
        self.verticalLayout_2.addWidget(self.name_entry)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setStyleSheet("color: rgb(77, 89, 89);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.email_entry = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_entry.sizePolicy().hasHeightForWidth())
        self.email_entry.setSizePolicy(sizePolicy)
        self.email_entry.setMinimumSize(QtCore.QSize(0, 50))
        self.email_entry.setStyleSheet("background-color: rgb(239, 240, 242);")
        self.email_entry.setFrame(False)
        self.email_entry.setObjectName("email_entry")
        self.verticalLayout_2.addWidget(self.email_entry)
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setStyleSheet("color: rgb(77, 89, 89);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.mobile_entry = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mobile_entry.sizePolicy().hasHeightForWidth())
        self.mobile_entry.setSizePolicy(sizePolicy)
        self.mobile_entry.setMinimumSize(QtCore.QSize(0, 50))
        self.mobile_entry.setStyleSheet("background-color: rgb(239, 240, 242);")
        self.mobile_entry.setInputMask("")
        self.mobile_entry.setFrame(False)
        self.mobile_entry.setObjectName("mobile_entry")
        self.verticalLayout_2.addWidget(self.mobile_entry)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setStyleSheet("color: rgb(77, 89, 89);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.password_1 = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_1.sizePolicy().hasHeightForWidth())
        self.password_1.setSizePolicy(sizePolicy)
        self.password_1.setMinimumSize(QtCore.QSize(0, 50))
        self.password_1.setStyleSheet("background-color: rgb(239, 240, 242);")
        self.password_1.setFrame(False)
        self.password_1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_1.setObjectName("password_1")
        self.verticalLayout_2.addWidget(self.password_1)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setStyleSheet("color: rgb(77, 89, 89);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.password_2 = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_2.sizePolicy().hasHeightForWidth())
        self.password_2.setSizePolicy(sizePolicy)
        self.password_2.setMinimumSize(QtCore.QSize(0, 50))
        self.password_2.setStyleSheet("background-color: rgb(239, 240, 242);")
        self.password_2.setFrame(False)
        self.password_2.setObjectName("password_2")
        self.verticalLayout_2.addWidget(self.password_2)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Submit_button = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Submit_button.sizePolicy().hasHeightForWidth())
        self.Submit_button.setSizePolicy(sizePolicy)
        self.Submit_button.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(14)
        self.Submit_button.setFont(font)
        self.Submit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Submit_button.setStyleSheet("background-color: rgb(0, 112, 116);\n"
"color: rgb(255, 255, 255);")
        self.Submit_button.setObjectName("Submit_button")
        self.verticalLayout_3.addWidget(self.Submit_button, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3.addWidget(self.frame_7, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "The Home for Hackathons \n"
"Internships & Many More"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Welcome to</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Full Name"))
        self.name_entry.setPlaceholderText(_translate("MainWindow", "    Enter your name"))
        self.label_2.setText(_translate("MainWindow", "Email"))
        self.email_entry.setPlaceholderText(_translate("MainWindow", "   Enter your Email here"))
        self.label_8.setText(_translate("MainWindow", "Mobile No."))
        self.mobile_entry.setPlaceholderText(_translate("MainWindow", "    Enter your mobile number"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.password_1.setPlaceholderText(_translate("MainWindow", "   Enter your Password"))
        self.label_4.setText(_translate("MainWindow", "Confirm Password"))
        self.password_2.setPlaceholderText(_translate("MainWindow", "   Re-enter Password"))
        self.Submit_button.setText(_translate("MainWindow", "Create Account"))
# import media_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_SignupWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
